// Vivado block design wrapper
module axi_write_buffer_wrapper #(
    parameter integer NumOutstanding = 32'd16,
    parameter integer WBufferDepth   = 32'd16,

    /// AXI
    /// Address width of all AXI4+ATOP ports
    parameter integer AddrWidth = 'd48,
    /// Data width of all AXI4+ATOP ports
    parameter integer DataWidth = 'd64,
    /// ID width of all AXI4+ATOP ports
    parameter integer IdWidth   = 'd4,
    /// User signal width of all AXI4+ATOP ports
    parameter integer UserWidth = 'd4
) (
    input clk,
    input resetn,

    output [$clog2(WBufferDepth):0] num_w_stored,
    output [$clog2(NumOutstanding):0] num_aw_stored,

    // Input ports
    input [IdWidth-1:0] s_axi_rt_0_awid,
    input [AddrWidth-1:0] s_axi_rt_0_awaddr,
    input [7:0] s_axi_rt_0_awlen,
    input [2:0] s_axi_rt_0_awsize,
    input [1:0] s_axi_rt_0_awburst,
    input s_axi_rt_0_awlock,
    input [3:0] s_axi_rt_0_awcache,
    input [2:0] s_axi_rt_0_awprot,
    input [3:0] s_axi_rt_0_awqos,
    input [UserWidth-1:0] s_axi_rt_0_awuser,
    input s_axi_rt_0_awvalid,
    output s_axi_rt_0_awready,
    input [DataWidth-1:0] s_axi_rt_0_wdata,
    input [7:0] s_axi_rt_0_wstrb,
    input s_axi_rt_0_wlast,
    input s_axi_rt_0_wvalid,
    output s_axi_rt_0_wready,
    output [IdWidth-1:0] s_axi_rt_0_bid,
    output [1:0] s_axi_rt_0_bresp,
    output s_axi_rt_0_bvalid,
    input s_axi_rt_0_bready,
    input [IdWidth-1:0] s_axi_rt_0_arid,
    input [AddrWidth-1:0] s_axi_rt_0_araddr,
    input [7:0] s_axi_rt_0_arlen,
    input [2:0] s_axi_rt_0_arsize,
    input [1:0] s_axi_rt_0_arburst,
    input s_axi_rt_0_arlock,
    input [3:0] s_axi_rt_0_arcache,
    input [2:0] s_axi_rt_0_arprot,
    input [3:0] s_axi_rt_0_arqos,
    input [UserWidth-1:0] s_axi_rt_0_aruser,
    input s_axi_rt_0_arvalid,
    output s_axi_rt_0_arready,
    output [IdWidth-1:0] s_axi_rt_0_rid,
    output [DataWidth-1:0] s_axi_rt_0_rdata,
    output [1:0] s_axi_rt_0_rresp,
    output s_axi_rt_0_rlast,
    output s_axi_rt_0_rvalid,
    input s_axi_rt_0_rready,

    // Output ports
    output [IdWidth-1:0] m_axi_rt_0_awid,
    output [AddrWidth-1:0] m_axi_rt_0_awaddr,
    output [7:0] m_axi_rt_0_awlen,
    output [2:0] m_axi_rt_0_awsize,
    output [1:0] m_axi_rt_0_awburst,
    output m_axi_rt_0_awlock,
    output [3:0] m_axi_rt_0_awcache,
    output [2:0] m_axi_rt_0_awprot,
    output [3:0] m_axi_rt_0_awqos,
    output [UserWidth-1:0] m_axi_rt_0_awuser,
    output m_axi_rt_0_awvalid,
    input m_axi_rt_0_awready,
    output [DataWidth-1:0] m_axi_rt_0_wdata,
    output [7:0] m_axi_rt_0_wstrb,
    output m_axi_rt_0_wlast,
    output m_axi_rt_0_wvalid,
    input m_axi_rt_0_wready,
    input [IdWidth-1:0] m_axi_rt_0_bid,
    input [1:0] m_axi_rt_0_bresp,
    input m_axi_rt_0_bvalid,
    output m_axi_rt_0_bready,
    output [IdWidth-1:0] m_axi_rt_0_arid,
    output [AddrWidth-1:0] m_axi_rt_0_araddr,
    output [7:0] m_axi_rt_0_arlen,
    output [2:0] m_axi_rt_0_arsize,
    output [1:0] m_axi_rt_0_arburst,
    output m_axi_rt_0_arlock,
    output [3:0] m_axi_rt_0_arcache,
    output [2:0] m_axi_rt_0_arprot,
    output [3:0] m_axi_rt_0_arqos,
    output [UserWidth-1:0] m_axi_rt_0_aruser,
    output m_axi_rt_0_arvalid,
    input m_axi_rt_0_arready,
    input [IdWidth-1:0] m_axi_rt_0_rid,
    input [DataWidth-1:0] m_axi_rt_0_rdata,
    input [1:0] m_axi_rt_0_rresp,
    input m_axi_rt_0_rlast,
    input m_axi_rt_0_rvalid,
    output m_axi_rt_0_rready
);
    // AXI RT unit, xilinx wrapper
    axi_write_buffer_flat #(
        .NumOutstanding(NumOutstanding),
        .WBufferDepth  (WBufferDepth),
        .AddrWidth     (AddrWidth),
        .DataWidth     (DataWidth),
        .IdWidth       (IdWidth),
        .UserWidth     (UserWidth)
    ) i_axi_write_buffer_flat (
        .clk_i (clk),
        .rst_ni(resetn),

        .num_w_stored_o (num_w_stored),
        .num_aw_stored_o(num_aw_stored),

        // Master
        .m_axi_rt_awid_o({m_axi_rt_0_awid}),
        .m_axi_rt_awaddr_o({m_axi_rt_0_awaddr}),
        .m_axi_rt_awlen_o({m_axi_rt_0_awlen}),
        .m_axi_rt_awsize_o({m_axi_rt_0_awsize}),
        .m_axi_rt_awburst_o({m_axi_rt_0_awburst}),
        .m_axi_rt_awlock_o({m_axi_rt_0_awlock}),
        .m_axi_rt_awcache_o({m_axi_rt_0_awcache}),
        .m_axi_rt_awprot_o({m_axi_rt_0_awprot}),
        .m_axi_rt_awqos_o({m_axi_rt_0_awqos}),
        .m_axi_rt_awuser_o({m_axi_rt_0_awuser}),
        .m_axi_rt_awvalid_o({m_axi_rt_0_awvalid}),
        .m_axi_rt_awready_i({m_axi_rt_0_awready}),
        .m_axi_rt_wdata_o({m_axi_rt_0_wdata}),
        .m_axi_rt_wstrb_o({m_axi_rt_0_wstrb}),
        .m_axi_rt_wlast_o({m_axi_rt_0_wlast}),
        .m_axi_rt_wvalid_o({m_axi_rt_0_wvalid}),
        .m_axi_rt_wready_i({m_axi_rt_0_wready}),
        .m_axi_rt_bid_i({m_axi_rt_0_bid}),
        .m_axi_rt_bresp_i({m_axi_rt_0_bresp}),
        .m_axi_rt_bvalid_i({m_axi_rt_0_bvalid}),
        .m_axi_rt_bready_o({m_axi_rt_0_bready}),
        .m_axi_rt_arid_o({m_axi_rt_0_arid}),
        .m_axi_rt_araddr_o({m_axi_rt_0_araddr}),
        .m_axi_rt_arlen_o({m_axi_rt_0_arlen}),
        .m_axi_rt_arsize_o({m_axi_rt_0_arsize}),
        .m_axi_rt_arburst_o({m_axi_rt_0_arburst}),
        .m_axi_rt_arlock_o({m_axi_rt_0_arlock}),
        .m_axi_rt_arcache_o({m_axi_rt_0_arcache}),
        .m_axi_rt_arprot_o({m_axi_rt_0_arprot}),
        .m_axi_rt_arqos_o({m_axi_rt_0_arqos}),
        .m_axi_rt_aruser_o({m_axi_rt_0_aruser}),
        .m_axi_rt_arvalid_o({m_axi_rt_0_arvalid}),
        .m_axi_rt_arready_i({m_axi_rt_0_arready}),
        .m_axi_rt_rid_i({m_axi_rt_0_rid}),
        .m_axi_rt_rdata_i({m_axi_rt_0_rdata}),
        .m_axi_rt_rresp_i({m_axi_rt_0_rresp}),
        .m_axi_rt_rlast_i({m_axi_rt_0_rlast}),
        .m_axi_rt_rvalid_i({m_axi_rt_0_rvalid}),
        .m_axi_rt_rready_o({m_axi_rt_0_rready}),

        // Slave
        .s_axi_rt_awid_i({s_axi_rt_0_awid}),
        .s_axi_rt_awaddr_i({s_axi_rt_0_awaddr}),
        .s_axi_rt_awlen_i({s_axi_rt_0_awlen}),
        .s_axi_rt_awsize_i({s_axi_rt_0_awsize}),
        .s_axi_rt_awburst_i({s_axi_rt_0_awburst}),
        .s_axi_rt_awlock_i({s_axi_rt_0_awlock}),
        .s_axi_rt_awcache_i({s_axi_rt_0_awcache}),
        .s_axi_rt_awprot_i({s_axi_rt_0_awprot}),
        .s_axi_rt_awqos_i({s_axi_rt_0_awqos}),
        .s_axi_rt_awuser_i({s_axi_rt_0_awuser}),
        .s_axi_rt_awvalid_i({s_axi_rt_0_awvalid}),
        .s_axi_rt_awready_o({s_axi_rt_0_awready}),
        .s_axi_rt_wdata_i({s_axi_rt_0_wdata}),
        .s_axi_rt_wstrb_i({s_axi_rt_0_wstrb}),
        .s_axi_rt_wlast_i({s_axi_rt_0_wlast}),
        .s_axi_rt_wvalid_i({s_axi_rt_0_wvalid}),
        .s_axi_rt_wready_o({s_axi_rt_0_wready}),
        .s_axi_rt_bid_o({s_axi_rt_0_bid}),
        .s_axi_rt_bresp_o({s_axi_rt_0_bresp}),
        .s_axi_rt_bvalid_o({s_axi_rt_0_bvalid}),
        .s_axi_rt_bready_i({s_axi_rt_0_bready}),
        .s_axi_rt_arid_i({s_axi_rt_0_arid}),
        .s_axi_rt_araddr_i({s_axi_rt_0_araddr}),
        .s_axi_rt_arlen_i({s_axi_rt_0_arlen}),
        .s_axi_rt_arsize_i({s_axi_rt_0_arsize}),
        .s_axi_rt_arburst_i({s_axi_rt_0_arburst}),
        .s_axi_rt_arlock_i({s_axi_rt_0_arlock}),
        .s_axi_rt_arcache_i({s_axi_rt_0_arcache}),
        .s_axi_rt_arprot_i({s_axi_rt_0_arprot}),
        .s_axi_rt_arqos_i({s_axi_rt_0_arqos}),
        .s_axi_rt_aruser_i({s_axi_rt_0_aruser}),
        .s_axi_rt_arvalid_i({s_axi_rt_0_arvalid}),
        .s_axi_rt_arready_o({s_axi_rt_0_arready}),
        .s_axi_rt_rid_o({s_axi_rt_0_rid}),
        .s_axi_rt_rdata_o({s_axi_rt_0_rdata}),
        .s_axi_rt_rresp_o({s_axi_rt_0_rresp}),
        .s_axi_rt_rlast_o({s_axi_rt_0_rlast}),
        .s_axi_rt_rvalid_o({s_axi_rt_0_rvalid}),
        .s_axi_rt_rready_i({s_axi_rt_0_rready})
    );
endmodule
