### Generated by vivamir.
# Do not edit manually.
#
# Common procedures and variables.
# Version 2.0.0

## Check if script is running in correct Vivado version.
set supported_vivado_version {2022.2}
set current_vivado_version [version -short]

if { [string first $current_vivado_version $supported_vivado_version] == -1 } {
   puts "The version $current_vivado_version is not supported. Supported versions are $supported_vivado_version"
   return 1
}

## Close the current project
if ![catch current_project] {
    close_project
}

## atexit
proc atexit { newbody } {
    if { [catch {set oldbody [info body exit]}] } {
        rename exit builtin_exit
        set oldbody { builtin_exit $returnCode }
    }

    proc exit { {returnCode 0} } [subst -nocommands {
        apply [list [list {returnCode 0}] [list $newbody]] \$returnCode
        apply [list [list {returnCode 0}] [list $oldbody]] \$returnCode
    }]
}

## rglob
proc rglob {dirlist globlist} {
    set result {}
    set recurse {}
    foreach dir $dirlist {
            if ![file isdirectory $dir] {
                    return -code error "'$dir' is not a directory"
            }
            foreach pattern $globlist {
                    lappend result {*}[glob -nocomplain -directory $dir -- $pattern]
            }
            foreach file [glob -nocomplain -directory $dir -- *] {
                    set file [file join $dir $file]
                    if [file isdirectory $file] {
                            set fileTail [file tail $file]
                            if {!($fileTail eq "." || $fileTail eq "..")} {
                                    lappend recurse $file
                            }
                    }
            }
    }
    if {[llength $recurse] > 0} {
            lappend result {*}[rglob $recurse $globlist]
    }
    return $result
}

## copytree
proc copytree {src dst skip} {
    foreach file [glob -directory $src -nocomplain *] {
        if [file isdirectory $file] {
            copytree $file [file join $dst [file rootname [file tail $file]]] $skip
        } else {
            if {![dict exists $skip $file]} {
                puts "$file -> $dst"
                file copy -force $file $dst    
            }
        }
    }
}

## Get root folder
set root [file dirname [file dirname [file normalize [info script]]]]
set root_name [file rootname [file tail $root]]

### From Vivamir
set project_name axi-rt

set block_designs [list \
    "$::root/test/bds/tbd_multidev.tcl" \
    "$::root/src/bds/tbd_multidev_synth.tcl" \
]
set includes [list \
    "include" \
    ".bender/git/checkouts/apb-283bf6e9432d6c92/include" \
    ".bender/git/checkouts/axi-7532a4b2723f5a17/include" \
    ".bender/git/checkouts/common_cells-66e79b7fa036356c/include" \
    ".bender/git/checkouts/register_interface-26fdd1b926642676/include" \
]
set des_filesets [list \
    "$::root/src" \
    "$::root/.bender/git/checkouts/apb-283bf6e9432d6c92/src" \
    "$::root/.bender/git/checkouts/axi-7532a4b2723f5a17/src" \
    "$::root/.bender/git/checkouts/common_cells-66e79b7fa036356c/src" \
    "$::root/.bender/git/checkouts/common_verification-86fda7a305e5991b/src" \
    "$::root/.bender/git/checkouts/register_interface-26fdd1b926642676/src" \
    "$::root/.bender/git/checkouts/register_interface-26fdd1b926642676/vendor/lowrisc_opentitan/src" \
    "$::root/.bender/git/checkouts/tech_cells_generic-ea5dabcb483cb44c/src" \
]
set des_filesets_read_only [list \
    "$::root/.bender/git/checkouts/apb-283bf6e9432d6c92/src" \
    "$::root/.bender/git/checkouts/axi-7532a4b2723f5a17/src" \
    "$::root/.bender/git/checkouts/common_cells-66e79b7fa036356c/src" \
    "$::root/.bender/git/checkouts/common_verification-86fda7a305e5991b/src" \
    "$::root/.bender/git/checkouts/register_interface-26fdd1b926642676/src" \
    "$::root/.bender/git/checkouts/register_interface-26fdd1b926642676/vendor/lowrisc_opentitan/src" \
    "$::root/.bender/git/checkouts/tech_cells_generic-ea5dabcb483cb44c/src" \
]
set sim_filesets [list \
    "$::root/test" \
]
set sim_filesets_read_only [list \

]
set ignores [list \
    .bender/git/checkouts/apb-*/src/apb_cdc.sv \
    .bender/git/checkouts/apb-*/src/apb_demux.sv \
    .bender/git/checkouts/apb-*/src/apb_err_slv.sv \
    .bender/git/checkouts/apb-*/src/apb_intf.sv \
    .bender/git/checkouts/apb-*/src/apb_pkg.sv \
    .bender/git/checkouts/apb-*/src/apb_regs.sv \
    .bender/git/checkouts/apb-*/src/apb_test.sv \
    .bender/git/checkouts/axi-*/src/axi_burst_splitter.sv \
    .bender/git/checkouts/axi-*/src/axi_bus_compare.sv \
    .bender/git/checkouts/axi-*/src/axi_cdc.sv \
    .bender/git/checkouts/axi-*/src/axi_cdc_dst.sv \
    .bender/git/checkouts/axi-*/src/axi_cdc_src.sv \
    .bender/git/checkouts/axi-*/src/axi_chan_compare.sv \
    .bender/git/checkouts/axi-*/src/axi_delayer.sv \
    .bender/git/checkouts/axi-*/src/axi_demux_simple.sv \
    .bender/git/checkouts/axi-*/src/axi_dumper.sv \
    .bender/git/checkouts/axi-*/src/axi_dw_converter.sv \
    .bender/git/checkouts/axi-*/src/axi_dw_downsizer.sv \
    .bender/git/checkouts/axi-*/src/axi_dw_upsizer.sv \
    .bender/git/checkouts/axi-*/src/axi_fifo.sv \
    .bender/git/checkouts/axi-*/src/axi_from_mem.sv \
    .bender/git/checkouts/axi-*/src/axi_id_prepend.sv \
    .bender/git/checkouts/axi-*/src/axi_id_remap.sv \
    .bender/git/checkouts/axi-*/src/axi_id_serialize.sv \
    .bender/git/checkouts/axi-*/src/axi_interleaved_xbar.sv \
    .bender/git/checkouts/axi-*/src/axi_intf.sv \
    .bender/git/checkouts/axi-*/src/axi_isolate.sv \
    .bender/git/checkouts/axi-*/src/axi_iw_converter.sv \
    .bender/git/checkouts/axi-*/src/axi_join.sv \
    .bender/git/checkouts/axi-*/src/axi_lfsr.sv \
    .bender/git/checkouts/axi-*/src/axi_lite_demux.sv \
    .bender/git/checkouts/axi-*/src/axi_lite_dw_converter.sv \
    .bender/git/checkouts/axi-*/src/axi_lite_from_mem.sv \
    .bender/git/checkouts/axi-*/src/axi_lite_join.sv \
    .bender/git/checkouts/axi-*/src/axi_lite_lfsr.sv \
    .bender/git/checkouts/axi-*/src/axi_lite_mailbox.sv \
    .bender/git/checkouts/axi-*/src/axi_lite_mux.sv \
    .bender/git/checkouts/axi-*/src/axi_lite_regs.sv \
    .bender/git/checkouts/axi-*/src/axi_lite_to_apb.sv \
    .bender/git/checkouts/axi-*/src/axi_lite_to_axi.sv \
    .bender/git/checkouts/axi-*/src/axi_lite_xbar.sv \
    .bender/git/checkouts/axi-*/src/axi_modify_address.sv \
    .bender/git/checkouts/axi-*/src/axi_mux.sv \
    .bender/git/checkouts/axi-*/src/axi_rw_join.sv \
    .bender/git/checkouts/axi-*/src/axi_rw_split.sv \
    .bender/git/checkouts/axi-*/src/axi_serializer.sv \
    .bender/git/checkouts/axi-*/src/axi_sim_mem.sv \
    .bender/git/checkouts/axi-*/src/axi_slave_compare.sv \
    .bender/git/checkouts/axi-*/src/axi_test.sv \
    .bender/git/checkouts/axi-*/src/axi_throttle.sv \
    .bender/git/checkouts/axi-*/src/axi_to_axi_lite.sv \
    .bender/git/checkouts/axi-*/src/axi_to_detailed_mem.sv \
    .bender/git/checkouts/axi-*/src/axi_to_mem.sv \
    .bender/git/checkouts/axi-*/src/axi_to_mem_banked.sv \
    .bender/git/checkouts/axi-*/src/axi_to_mem_interleaved.sv \
    .bender/git/checkouts/axi-*/src/axi_to_mem_split.sv \
    .bender/git/checkouts/axi-*/src/axi_xbar.sv \
    .bender/git/checkouts/axi-*/src/axi_xbar_unmuxed.sv \
    .bender/git/checkouts/axi-*/src/axi_xp.sv \
    .bender/git/checkouts/axi-*/src/axi_zero_mem.sv \
    .bender/git/checkouts/axi_rt-*/src/axi_rt_unit_top_synth.sv \
    .bender/git/checkouts/common_cells-*/src/addr_decode.sv \
    .bender/git/checkouts/common_cells-*/src/addr_decode_napot.sv \
    .bender/git/checkouts/common_cells-*/src/binary_to_gray.sv \
    .bender/git/checkouts/common_cells-*/src/cb_filter.sv \
    .bender/git/checkouts/common_cells-*/src/cb_filter_pkg.sv \
    .bender/git/checkouts/common_cells-*/src/cc_onehot.sv \
    .bender/git/checkouts/common_cells-*/src/cdc_2phase.sv \
    .bender/git/checkouts/common_cells-*/src/cdc_2phase_clearable.sv \
    .bender/git/checkouts/common_cells-*/src/cdc_4phase.sv \
    .bender/git/checkouts/common_cells-*/src/cdc_fifo_2phase.sv \
    .bender/git/checkouts/common_cells-*/src/cdc_fifo_gray.sv \
    .bender/git/checkouts/common_cells-*/src/cdc_fifo_gray_clearable.sv \
    .bender/git/checkouts/common_cells-*/src/cdc_reset_ctrlr.sv \
    .bender/git/checkouts/common_cells-*/src/cdc_reset_ctrlr_pkg.sv \
    .bender/git/checkouts/common_cells-*/src/clk_int_div.sv \
    .bender/git/checkouts/common_cells-*/src/clk_int_div_static.sv \
    .bender/git/checkouts/common_cells-*/src/clk_mux_glitch_free.sv \
    .bender/git/checkouts/common_cells-*/src/credit_counter.sv \
    .bender/git/checkouts/common_cells-*/src/ecc_decode.sv \
    .bender/git/checkouts/common_cells-*/src/ecc_encode.sv \
    .bender/git/checkouts/common_cells-*/src/ecc_pkg.sv \
    .bender/git/checkouts/common_cells-*/src/edge_detect.sv \
    .bender/git/checkouts/common_cells-*/src/edge_propagator.sv \
    .bender/git/checkouts/common_cells-*/src/edge_propagator_ack.sv \
    .bender/git/checkouts/common_cells-*/src/edge_propagator_rx.sv \
    .bender/git/checkouts/common_cells-*/src/edge_propagator_tx.sv \
    .bender/git/checkouts/common_cells-*/src/exp_backoff.sv \
    .bender/git/checkouts/common_cells-*/src/fall_through_register.sv \
    .bender/git/checkouts/common_cells-*/src/gray_to_binary.sv \
    .bender/git/checkouts/common_cells-*/src/isochronous_4phase_handshake.sv \
    .bender/git/checkouts/common_cells-*/src/isochronous_spill_register.sv \
    .bender/git/checkouts/common_cells-*/src/lfsr.sv \
    .bender/git/checkouts/common_cells-*/src/lfsr_16bit.sv \
    .bender/git/checkouts/common_cells-*/src/lfsr_8bit.sv \
    .bender/git/checkouts/common_cells-*/src/lossy_valid_to_stream.sv \
    .bender/git/checkouts/common_cells-*/src/max_counter.sv \
    .bender/git/checkouts/common_cells-*/src/mem_to_banks.sv \
    .bender/git/checkouts/common_cells-*/src/mem_to_banks_detailed.sv \
    .bender/git/checkouts/common_cells-*/src/multiaddr_decode.sv \
    .bender/git/checkouts/common_cells-*/src/mv_filter.sv \
    .bender/git/checkouts/common_cells-*/src/passthrough_stream_fifo.sv \
    .bender/git/checkouts/common_cells-*/src/plru_tree.sv \
    .bender/git/checkouts/common_cells-*/src/popcount.sv \
    .bender/git/checkouts/common_cells-*/src/read.sv \
    .bender/git/checkouts/common_cells-*/src/rr_arb_tree.sv \
    .bender/git/checkouts/common_cells-*/src/rstgen.sv \
    .bender/git/checkouts/common_cells-*/src/rstgen_bypass.sv \
    .bender/git/checkouts/common_cells-*/src/serial_deglitch.sv \
    .bender/git/checkouts/common_cells-*/src/shift_reg.sv \
    .bender/git/checkouts/common_cells-*/src/shift_reg_gated.sv \
    .bender/git/checkouts/common_cells-*/src/stream_delay.sv \
    .bender/git/checkouts/common_cells-*/src/stream_demux.sv \
    .bender/git/checkouts/common_cells-*/src/stream_fifo_optimal_wrap.sv \
    .bender/git/checkouts/common_cells-*/src/stream_filter.sv \
    .bender/git/checkouts/common_cells-*/src/stream_fork.sv \
    .bender/git/checkouts/common_cells-*/src/stream_fork_dynamic.sv \
    .bender/git/checkouts/common_cells-*/src/stream_intf.sv \
    .bender/git/checkouts/common_cells-*/src/stream_mux.sv \
    .bender/git/checkouts/common_cells-*/src/stream_omega_net.sv \
    .bender/git/checkouts/common_cells-*/src/stream_throttle.sv \
    .bender/git/checkouts/common_cells-*/src/stream_to_mem.sv \
    .bender/git/checkouts/common_cells-*/src/stream_xbar.sv \
    .bender/git/checkouts/common_cells-*/src/sub_per_hash.sv \
    .bender/git/checkouts/common_cells-*/src/sync.sv \
    .bender/git/checkouts/common_cells-*/src/sync_wedge.sv \
    .bender/git/checkouts/common_cells-*/src/unread.sv \
    .bender/git/checkouts/common_cells-*/src/deprecated/* \
    .bender/git/checkouts/common_verification-*/src/clk_rst_gen.sv \
    .bender/git/checkouts/common_verification-*/src/rand_id_queue.sv \
    .bender/git/checkouts/common_verification-*/src/rand_stream_mst.sv \
    .bender/git/checkouts/common_verification-*/src/rand_stream_slv.sv \
    .bender/git/checkouts/common_verification-*/src/rand_synch_driver.sv \
    .bender/git/checkouts/common_verification-*/src/rand_synch_holdable_driver.sv \
    .bender/git/checkouts/common_verification-*/src/rand_verif_pkg.sv \
    .bender/git/checkouts/common_verification-*/src/signal_highlighter.sv \
    .bender/git/checkouts/common_verification-*/src/sim_timeout.sv \
    .bender/git/checkouts/common_verification-*/src/stream_watchdog.sv \
    .bender/git/checkouts/register_interface-*/src/apb_to_reg.sv \
    .bender/git/checkouts/register_interface-*/src/axi_to_reg_v2.sv \
    .bender/git/checkouts/register_interface-*/src/periph_to_reg.sv \
    .bender/git/checkouts/register_interface-*/src/reg_cdc.sv \
    .bender/git/checkouts/register_interface-*/src/reg_cut.sv \
    .bender/git/checkouts/register_interface-*/src/reg_filter_empty_writes.sv \
    .bender/git/checkouts/register_interface-*/src/reg_intf.sv \
    .bender/git/checkouts/register_interface-*/src/reg_mux.sv \
    .bender/git/checkouts/register_interface-*/src/reg_test.sv \
    .bender/git/checkouts/register_interface-*/src/reg_to_apb.sv \
    .bender/git/checkouts/register_interface-*/src/reg_to_axi.sv \
    .bender/git/checkouts/register_interface-*/src/reg_to_mem.sv \
    .bender/git/checkouts/register_interface-*/src/reg_to_tlul.sv \
    .bender/git/checkouts/register_interface-*/src/reg_uniform.sv \
    .bender/git/checkouts/register_interface-*/src/deprecated/axi_to_reg.sv \
    .bender/git/checkouts/register_interface-*/src/test/* \
    .bender/git/checkouts/tech_cells_generic-*/src/tc_pwr.sv \
    .bender/git/checkouts/tech_cells_generic-*/src/deprecated/* \
    .bender/git/checkouts/tech_cells_generic-*/src/fpga/pad_functional_xilinx.sv \
    .bender/git/checkouts/tech_cells_generic-*/src/fpga/tc_clk_xilinx.sv \
    .bender/git/checkouts/tech_cells_generic-*/src/fpga/tc_sram_xilinx.sv \
    .bender/git/checkouts/tech_cells_generic-*/src/rtl/tc_clk.sv \
    .bender/git/checkouts/tech_cells_generic-*/src/rtl/tc_sram.sv \
    .bender/git/checkouts/tech_cells_generic-*/src/rtl/tc_sram_impl.sv \
    test/tb_axi_rt_unit_top.sv \
    test/stimuli/* \
]

## Export
proc vivamir_export_bds {} {
    set block_designs_name_to_path {}
    foreach file $::block_designs {
        dict set block_designs_name_to_path [file rootname [file tail $file]] $file
    }

    foreach bd [get_files *.bd] {
        set errored [catch {
            open_bd_design $bd
            set name [file rootname [file tail $bd]]

            set output $::root/src/bds/$name.tcl
            if [dict exists $block_designs_name_to_path $name] {
                set output [dict get $block_designs_name_to_path $name]
            }

            write_bd_tcl -force $output
            close_bd_design [current_bd_design]
        } emsg]
        if {$errored} {
            puts $emsg
        }
    }
}

proc vivamir_export_fileset {kind {new_file_dst $::root}} {
    set ignore_files_dict {}
    foreach ignore $::ignores {
        foreach file [glob -nocomplain -directory $::root -- $ignore] {
            dict set ignore_files_dict $file ""
        }
    }

    set skip {}
    foreach file [rglob $::des_filesets_read_only {*.*}] {
        if {![dict exists $ignore_files_dict $file]} {
            dict set skip $file ""
        }
    }
    foreach file [rglob $::sim_filesets_read_only {*.*}] {
        if {![dict exists $ignore_files_dict $file]} {
            dict set skip $file ""
        }
    }

    set imports [lindex [glob $::root/vivamir/project/$::project_name.srcs/$kind/imports/*] 0]
    copytree $imports $::root $skip

    set new_file_dst {}
    dict set new_file_dst sources_1 $::root/src
    dict set new_file_dst sim_1 $::root/test

    foreach file [get_files -quiet $::root/vivamir/project/$::project_name.srcs/$kind/new/*] {
        file copy $file [dict get $new_file_dst $kind]
    }
}
