### Generated by vivamir.
# Do not edit manually.
#
# Exports BDs and sources.
# Version 2.0.0

### Commons
source commons.tcl

### Open project
open_project $::root/vivamir/project/$::project_name.xpr

### Export BDs
vivamir_export_bds

### Export sources
vivamir_export_fileset sources_1
vivamir_export_fileset sim_1
