### Generated by vivamir.
# Do not edit manually.
#
# Starts the GUI after setting up a fresh project.
# Version 1.1.0

### Create the project.
source project.tcl

### Start GUI
## Export at exit (disabled due to issues with stdin on `vivamir open`)
# atexit {
#     puts stdout {Confirm export? [y/N]}
#     puts stdout {This will overwrite files!}
#     flush stdout
#     if {[string first y [gets stdin]] == 0} {
#         source export.tcl
#     }
# }

## Continue logging to terminal
# set pid [exec tail -n0 -f $::root/vivamir/vivado.log &]

## Wait for successful start (useful on macOS)
while 1 {
    set errored [catch start_gui emsg]
    if {!$errored} break

    puts [string trimright $emsg]
    puts "start_gui failed, waiting for input to retry (or close after Ctrl+C)."
    gets stdin
}
