### Generated by vivamir.
# Do not edit manually.
#
# Creates the project.
# Version 2.1.0

### Commons
source commons.tcl

## Expand
set ignore_files_dict {}
foreach ignore $::ignores {
    foreach file [glob -nocomplain -directory $::root -- $ignore] {
        dict set ignore_files_dict $file ""
    }
}

set valid_extensions {}
dict set valid_extensions .v ""
dict set valid_extensions .vh ""
dict set valid_extensions .sv ""
dict set valid_extensions .svh ""
dict set valid_extensions .vhdl ""

set des_files {}
foreach file [rglob $des_filesets {*.*}] {
    if {[dict exists $valid_extensions [file extension $file]] && ![dict exists $ignore_files_dict $file]} {
        lappend des_files $file
    }
}

set sim_files {}
foreach file [rglob $sim_filesets {*.*}] {
    if {[dict exists $valid_extensions [file extension $file]] && ![dict exists $ignore_files_dict $file]} {
        lappend sim_files $file
    }
}

### Force create project
create_project $project_name $::root/vivamir/project -part xck26-sfvc784-2LV-c -force

### Design files
add_files -fileset sources_1 -norecurse $des_files
set includes_absolute {}
foreach include $includes {
    lappend includes_absolute $::root/$include
}
add_files -fileset sources_1 $includes_absolute
import_files -relative_to $root -fileset sources_1

### Includes
set includes_imported {}
foreach include $includes {
    lappend includes_imported $::root/vivamir/project/$project_name.srcs/sources_1/imports/$root_name/$include
}
set_property include_dirs $includes_imported [get_filesets sources_1]
# TODO: Includes work only as globals?
foreach include $includes_imported {
    set_property is_global_include true [get_files $include/*]
}

### Simulation files
add_files -fileset sim_1 -norecurse $sim_files
import_files -relative_to $root -fileset sim_1

### Load user IPs
set_property ip_repo_paths $::root/ips [current_project]
update_ip_catalog

### Block Designs
foreach bd $block_designs {
    # Source Tcl
    source -notrace $bd

    # Validate BD
    regenerate_bd_layout
    validate_bd_design 
    save_bd_design

    # Generate wrapper
    make_wrapper -fileset sources_1 -top [get_files ${design_name}.bd] 

    # Add wrapper
    add_files -fileset sources_1 "$::root/vivamir/project/${project_name}.gen/sources_1/bd/${design_name}/hdl/${design_name}_wrapper.v"                
}

### Top modules
set_property top_lib xil_defaultlib [get_filesets sources_1]
set_property top {bd_dpu_wrapper} [get_filesets sources_1]

set_property top_lib xil_defaultlib [get_filesets sim_1]
set_property top {tbd_multidev_run} [get_filesets sim_1]
set_property -name xsim.view -value "$::root/test/tbd_multidev_run.wcfg" -object [get_filesets sim_1]

### User Settings
set_property -name xsim.simulate.runtime -value 0ps -object [get_filesets sim_1]
set_property -name xsim.simulate.log_all_signals -value true -object [get_filesets sim_1]
set_property -name xsim.elaborate.mt_level -value 32 -object [get_filesets sim_1]

### Update
update_compile_order -fileset sources_1
update_compile_order -fileset sim_1
