### Generated by vivamir.
# Do not edit manually.
#
# Creates the project.
# Version 2.1.0

### Commons
source commons.tcl

## Expand
set ignore_files_dict {}
foreach ignore $::ignores {
    foreach file [glob -nocomplain -directory $::root -- $ignore] {
        dict set ignore_files_dict $file ""
    }
}

set valid_extensions {}
dict set valid_extensions .v ""
dict set valid_extensions .vh ""
dict set valid_extensions .sv ""
dict set valid_extensions .svh ""
dict set valid_extensions .vhdl ""

set des_files {}
foreach file [rglob $des_filesets {*.*}] {
    if {[dict exists $valid_extensions [file extension $file]] && ![dict exists $ignore_files_dict $file]} {
        lappend des_files $file
    }
}

set sim_files {}
foreach file [rglob $sim_filesets {*.*}] {
    if {[dict exists $valid_extensions [file extension $file]] && ![dict exists $ignore_files_dict $file]} {
        lappend sim_files $file
    }
}

set inc_files {}
foreach file [rglob $includes {*.*}] {
    if {[dict exists $valid_extensions [file extension $file]] && ![dict exists $ignore_files_dict $file]} {
        lappend inc_files $file
    }
}

### Force create project
create_project $project_name $::root/vivamir/project -part xck26-sfvc784-2LV-c -force
set_property -name "board_part" -value xilinx.com:kr260_som:part0:1.1 -objects [current_project]
set_property -name "platform.board_id" -value kr260_som -objects [current_project]

### Design files
add_files -fileset sources_1 -norecurse $des_files
add_files -fileset sources_1 -norecurse $inc_files
import_files -relative_to $root -fileset sources_1

### Includes
set includes_imported {}
foreach include $includes {
    set include_rel [string replace $include 0 [string len $::root]]
    lappend includes_imported $::root/vivamir/project/$project_name.srcs/sources_1/imports/$root_name/$include_rel
}
set_property include_dirs $includes_imported [get_filesets sources_1]
# TODO: Includes work only as globals?
foreach include $includes_imported {
    catch {
        set_property is_global_include true [get_files -quiet $include/*]
    }
}

### Simulation files
add_files -fileset sim_1 -norecurse $sim_files
import_files -relative_to $root -fileset sim_1

### Load user IPs
set_property ip_repo_paths $::root/ips [current_project]
update_ip_catalog

### Block Designs
foreach bd $block_designs {
    # Source Tcl
    source -notrace $bd

    # Generate wrapper
    make_wrapper -fileset sources_1 -top [get_files ${design_name}.bd] 

    # Add wrapper
    add_files -fileset sources_1 "$::root/vivamir/project/${project_name}.gen/sources_1/bd/${design_name}/hdl/${design_name}_wrapper.v"                
}

### Top modules
set_property top_lib xil_defaultlib [get_filesets sources_1]
set_property top {tbd_multidev_synth_wrapper} [get_filesets sources_1]

set_property top_lib xil_defaultlib [get_filesets sim_1]
set_property top {tbd_multidev_run} [get_filesets sim_1]
set_property -name xsim.view -value "$::root/test/tbd_multidev_run.wcfg" -object [get_filesets sim_1]

### User Settings
set_property -name xsim.simulate.runtime -value 0ps -object [get_filesets sim_1]
set_property -name xsim.simulate.log_all_signals -value true -object [get_filesets sim_1]
set_property -name xsim.elaborate.mt_level -value 32 -object [get_filesets sim_1]

### Update
update_compile_order -fileset sources_1
update_compile_order -fileset sim_1
